---
title: "class_gentrifizerungsdruck"
output: html_document
date: "2022-10-21"
---


```{r}
library(rvest)
library(dplyr)
library(readr)
```

# Mietpreis 2019 nach bezirk 
```{r}
link <- "https://www.homeday.de/de/blog/mietpreise-berlin-2019/"
page = read_html(link)

vektor_rent <- page %>%
  html_nodes("td") %>%
  html_text()
```

```{r}

scrape_website <- function(Name, Anfangsposition){
Name <- c()
i=Anfangsposition
while (i < length(vektor_rent)) {
  print(i)
  print(vektor_rent[i])
  Name <- append(Name, vektor_rent[i])
  i=i+4
}
return(Name)
}
```

```{r}

df_bezirk <- data.frame(scrape_website(Bezirk, 1), 
                       scrape_website(Mietpreis_2019, 3)
) %>%
  rename(Bezirk=scrape_website.Bezirk..1., 
         Mietpreis2019 = scrape_website.Mietpreis_2019..3.)

## erase euro symbol and make integer 

library(stringr)
df_bezirk$Mietpreis2019 <- str_replace(df_bezirk$Mietpreis2019, " €", "")
df_bezirk$Mietpreis2019 <- str_replace(df_bezirk$Mietpreis2019, ",", ".")  
df_bezirk$Mietpreis2019 <- as.numeric(df_bezirk$Mietpreis2019)
```

```{r}
write_csv(df_bezirk, "data/berlin_rental_market/Mietpreise_nach_Bezirk")
```

# Postal Codes 


```{r}
link_2 <- "https://www.berlinstadtservice.de/xinh/Postleitzahlen_Berlin_Alphabetisch.html"

page_2 = read_html(link_2)

Bezirke_plz <- page_2 %>%
  html_nodes("td") %>%
  html_text()
```

```{r}
df_Bezirke_plz <- data.frame(Bezirke_plz)
df_bezirke_plz_2 <- data.frame(str_split_fixed(df_Bezirke_plz$Bezirke_plz, " ", 2))
df_bezirke_plz_2$X2 <- str_remove_all(df_bezirke_plz_2$X2, "B- ")
df_bezirke_plz_2$X2 <- str_remove_all(df_bezirke_plz_2$X2, "B-")

df_bezirke_plz_2$X1 <- as.integer(df_bezirke_plz_2$X1)

df_bezirke_plz_2 <- data.frame(df_bezirke_plz_2)
```

# Read Immo Data 
```{r}
immoscout <- read_csv("../data/berlin_rental_market/immoscout.csv", sep=";") %>%
  select(ZIP_Code, sqm_price)
```

# Merge Datasets 

```{r}
immoscout_bezirke <- left_join(immoscout,
            df_bezirke_plz_2, 
            by=c("ZIP_Code" = "X1"))

immoscout_bezirke_price <- left_join(immoscout_bezirke, 
                                     df_bezirk, 
                                     by = c("X2" = "Bezirk"))

bezirke_abweichung <- immoscout_bezirke_price %>%
  mutate(abweichung_durchschnitt = sqm_price - Mietpreis2019)
```

```{r}

bezirke_abweichung %>%
  filter(!is.na(Mietpreis2019)) %>%
  filter(!is.na(sqm_price)) %>%
  group_by(X2) %>%
  summarise(mean_abweichung = mean(abweichung_durchschnitt), 
            n_cases = n()) %>%
  arrange(desc(mean_abweichung))
``` 
# Plot data 

```{r}

```

